apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-docs-api
  labels:
    driveby.io/version: "2.0.0"
    app: bad-docs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-docs-api
  template:
    metadata:
      labels:
        driveby.io/version: "2.0.0"
        app: bad-docs-api
    spec:
      containers:
        - name: api
          image: ghcr.io/novelcore/bad-docs-api:f0f87800301755603dae71e75380d8d95bde1362
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              value: "driveby-test-key-2024"
          livenessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 3
      imagePullSecrets:
        - name: ghcr-creds
